"""Error codes for study material operations."""

# File and directory errors
FILE_NOT_FOUND = "FILE_NOT_FOUND"
INVALID_FILE_FORMAT = "INVALID_FILE_FORMAT"
DIRECTORY_NOT_FOUND = "DIRECTORY_NOT_FOUND"

# Validation errors
INVALID_QUERY = "INVALID_QUERY"
INVALID_TOPIC = "INVALID_TOPIC"
INVALID_TOPICS = "INVALID_TOPICS"
EMPTY_MATERIALS = "EMPTY_MATERIALS"

# Processing errors
DOCUMENT_PROCESSING_FAILED = "DOCUMENT_PROCESSING_FAILED"
EMBEDDING_GENERATION_FAILED = "EMBEDDING_GENERATION_FAILED"
CATEGORIZATION_FAILED = "CATEGORIZATION_FAILED"
COMPARISON_FAILED = "COMPARISON_FAILED"

# General errors
INTERNAL_ERROR = "INTERNAL_ERROR"
OPERATION_FAILED = "OPERATION_FAILED"
